version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app

jobs:
  run-docker:
    executor: docker-executor
    parameters:
      run_id:
        type: string
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.24

      - run:
          name: Pull Docker image
          command: |
            docker pull nduythanh1/selenium-chrome-app
            docker pull nduythanh1/streamhg-chrome-app

      - run:
          name: Run container with timeout 15 minutes (hard limit)
          command: |
            echo "Running job with parameter: << parameters.run_id >>"
      
            # Start container in background and save container ID
            docker run -d --rm \
              --name selenium_<< parameters.run_id >> \
              -e RUN_ID=<< parameters.run_id >> \
              nduythanh1/selenium-chrome-app > cid.txt
      
            CID=$(cat cid.txt)
      
            # Wait for up to 15 minutes (900 seconds), then kill if needed
            (docker wait $CID & echo $! > wait_pid.txt) &
      
            sleep 900 && echo "Timeout reached! Killing container..." && docker kill $CID || true
      
            # Ensure wait finishes so CI job doesn't hang
            wait $(cat wait_pid.txt) || true

            echo "Container completed or was terminated"
      - run:
          name: Run 2 streamhg-chrome-app containers in parallel
          command: |
            echo "Starting 2 streamhg-chrome-app containers for RUN_ID: << parameters.run_id >>"

            timeout 7m docker run --rm \
              -e RUN_ID=<< parameters.run_id >>_a \
              nduythanh1/streamhg-chrome-app > stream1_<< parameters.run_id >>.log 2>&1 &

            timeout 7m docker run --rm \
              -e RUN_ID=<< parameters.run_id >>_b \
              nduythanh1/streamhg-chrome-app > stream2_<< parameters.run_id >>.log 2>&1 &

            wait
            echo "Finished both streamhg-chrome-app for RUN_ID: << parameters.run_id >>"

workflows:
  run-parallel:
    jobs:
      - run-docker:
          matrix:
            parameters:
              run_id: ["job1", "job2", "job3", "job4", "job5"]
